import { ArrowLeft, Download, Factory, PackageSearch, Printer, RefreshCw } from "lucide-react";
import { useMemo, useState } from "react";
import Layout from "@/components/Layout";
import { useI18n } from "@/i18n";
import { exportReportExcel, printReport, type ReportColumn } from "@/lib/reportExport";

type InventoryReport = { title: string; description: string; columns: ReportColumn[]; rows: Record<string, string | number>[] };

const sampleRows = [
  { date: "2026-08-02", item: "قميص بوليستر بشعار", warehouse: "المستودع الرئيسي", inbound: 120, outbound: 0, balance: 120 },
  { date: "2026-08-09", item: "قبعة بشعار", warehouse: "المستودع الرئيسي", inbound: 80, outbound: 20, balance: 60 },
  { date: "2026-08-15", item: "جاكيت شيف أسود", warehouse: "مستودع جدة", inbound: 50, outbound: 12, balance: 38 },
  { date: "2026-08-22", item: "حقيبة تسوق", warehouse: "المستودع الرئيسي", inbound: 100, outbound: 35, balance: 65 },
];

const reports: InventoryReport[] = [
  { title: "حركة المخزون", description: "حركات الإدخال والإخراج والأرصدة حسب الصنف", columns: [{ key: "date", label: "التاريخ" }, { key: "item", label: "الصنف" }, { key: "warehouse", label: "المستودع" }, { key: "inbound", label: "وارد" }, { key: "outbound", label: "صادر" }, { key: "balance", label: "الرصيد" }], rows: sampleRows },
  { title: "الملخص الشهري للمخزون", description: "ملخص شهري للكميات الواردة والصادرة", columns: [{ key: "month", label: "الشهر" }, { key: "warehouse", label: "المستودع" }, { key: "inbound", label: "إجمالي الوارد" }, { key: "outbound", label: "إجمالي الصادر" }, { key: "balance", label: "الرصيد الختامي" }], rows: [{ month: "أغسطس 2026", warehouse: "المستودع الرئيسي", inbound: 300, outbound: 55, balance: 245 }, { month: "أغسطس 2026", warehouse: "مستودع جدة", inbound: 50, outbound: 12, balance: 38 }] },
  { title: "سجل الإنتاج", description: "أوامر الإنتاج المنجزة وقيد التنفيذ", columns: [{ key: "number", label: "رقم الأمر" }, { key: "date", label: "التاريخ" }, { key: "item", label: "المنتج" }, { key: "quantity", label: "الكمية" }, { key: "status", label: "الحالة" }], rows: [{ number: "PRO-0001", date: "2026-08-05", item: "قميص بوليستر بشعار", quantity: 120, status: "مكتمل" }, { number: "PRO-0002", date: "2026-08-18", item: "جاكيت شيف أسود", quantity: 50, status: "قيد التنفيذ" }] },
  { title: "تكلفة البضاعة المصنعة", description: "تكلفة المواد والعمل والتكاليف الصناعية", columns: [{ key: "product", label: "المنتج" }, { key: "materials", label: "المواد" }, { key: "labor", label: "العمل" }, { key: "overhead", label: "التكاليف الصناعية" }, { key: "total", label: "إجمالي التكلفة" }], rows: [{ product: "قميص بوليستر بشعار", materials: "3,600.00", labor: "1,200.00", overhead: "600.00", total: "5,400.00" }, { product: "جاكيت شيف أسود", materials: "2,500.00", labor: "900.00", overhead: "450.00", total: "3,850.00" }] },
  { title: "انحراف تكلفة التصنيع", description: "مقارنة التكلفة الفعلية بالمخططة", columns: [{ key: "product", label: "المنتج" }, { key: "planned", label: "التكلفة المخططة" }, { key: "actual", label: "التكلفة الفعلية" }, { key: "variance", label: "الانحراف" }, { key: "percent", label: "نسبة الانحراف" }], rows: [{ product: "قميص بوليستر بشعار", planned: "5,200.00", actual: "5,400.00", variance: "200.00", percent: "3.85%" }, { product: "جاكيت شيف أسود", planned: "4,000.00", actual: "3,850.00", variance: "-150.00", percent: "-3.75%" }] },
  { title: "الإنتاج تحت التشغيل", description: "أوامر الإنتاج التي لم تكتمل", columns: [{ key: "number", label: "رقم الأمر" }, { key: "product", label: "المنتج" }, { key: "started", label: "تاريخ البدء" }, { key: "progress", label: "نسبة الإنجاز" }, { key: "cost", label: "تكلفة تحت التشغيل" }], rows: [{ number: "PRO-0002", product: "جاكيت شيف أسود", started: "2026-08-18", progress: "60%", cost: "2,310.00" }] },
  { title: "احتياجات مواد الإنتاج", description: "المواد المطلوبة لأوامر الإنتاج المفتوحة", columns: [{ key: "product", label: "المنتج" }, { key: "material", label: "المادة" }, { key: "required", label: "المطلوب" }, { key: "available", label: "المتوفر" }, { key: "shortage", label: "العجز" }], rows: [{ product: "جاكيت شيف أسود", material: "قماش أسود", required: 100, available: 70, shortage: 30 }, { product: "جاكيت شيف أسود", material: "شعار مطرز", required: 50, available: 65, shortage: 0 }] },
  { title: "استهلاك مواد الإنتاج", description: "استهلاك المواد الفعلي حسب أمر الإنتاج", columns: [{ key: "number", label: "رقم الأمر" }, { key: "material", label: "المادة" }, { key: "planned", label: "المخطط" }, { key: "actual", label: "المستهلك فعلياً" }, { key: "variance", label: "الانحراف" }], rows: [{ number: "PRO-0001", material: "قماش بوليستر", planned: 240, actual: 245, variance: 5 }, { number: "PRO-0001", material: "شعار مطرز", planned: 120, actual: 120, variance: 0 }] },
];

export default function InventoryReports() {
  const { t, direction } = useI18n();
  const [selected, setSelected] = useState<InventoryReport>(reports[0]);
  const [dateFrom, setDateFrom] = useState("2026-05-01");
  const [dateTo, setDateTo] = useState("2026-08-31");
  const exportOptions = useMemo(() => ({ title: t(selected.title), subtitle: `${t("بيانات مثال")} — ${dateFrom} ${t("إلى")} ${dateTo}`, columns: selected.columns.map((column) => ({ ...column, label: t(column.label) })), rows: selected.rows, fileName: selected.title, landscape: true }), [dateFrom, dateTo, selected, t]);

  return <Layout><main dir={direction} className="min-h-full bg-slate-50 p-4"><div className="mx-auto max-w-[1500px] overflow-hidden rounded border border-slate-200 bg-white shadow-sm">
    <header className="border-t-2 border-red-700 px-4 py-2"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[11px] text-slate-400">{t("المخزون")} / {t("التقارير")}</p><h1 className="text-sm font-bold text-slate-800">{t(selected.title)}</h1></div><div className="flex gap-1"><button onClick={() => setSelected({ ...selected })} className="rounded border border-slate-200 p-1.5" title={t("تحديث")}><RefreshCw className="h-3.5 w-3.5" /></button><button onClick={() => printReport(exportOptions)} className="rounded border border-slate-200 p-1.5" title={t("طباعة")}><Printer className="h-3.5 w-3.5" /></button><button onClick={() => exportReportExcel(exportOptions)} className="rounded border border-slate-200 p-1.5" title={t("تصدير Excel")}><Download className="h-3.5 w-3.5" /></button></div></div></header>
    <div className="grid grid-cols-2 border-b border-slate-100 md:grid-cols-4">{reports.map((report) => <button key={report.title} onClick={() => setSelected(report)} className={`border-s border-b border-slate-100 px-3 py-3 text-xs font-semibold ${selected.title === report.title ? "bg-slate-800 text-white" : "text-slate-600 hover:bg-slate-50"}`}>{t(report.title)}</button>)}</div>
    <div className="flex flex-wrap items-end justify-between gap-3 border-b border-slate-100 bg-slate-50 px-4 py-3"><div className="flex gap-2"><label className="text-xs text-slate-500">{t("من تاريخ")}<input type="date" value={dateFrom} onChange={(event) => setDateFrom(event.target.value)} className="mt-1 block rounded border border-slate-200 bg-white px-2 py-1.5 text-xs" /></label><label className="text-xs text-slate-500">{t("إلى تاريخ")}<input type="date" value={dateTo} onChange={(event) => setDateTo(event.target.value)} className="mt-1 block rounded border border-slate-200 bg-white px-2 py-1.5 text-xs" /></label></div><span className="rounded bg-amber-50 px-2 py-1 text-[11px] font-semibold text-amber-700">{t("بيانات مثال")}</span></div>
    <section className="p-4"><p className="mb-3 text-xs text-slate-500">{t(selected.description)}</p><div className="overflow-x-auto"><table className="min-w-full text-xs"><thead className="bg-slate-100 text-slate-700"><tr>{selected.columns.map((column) => <th key={column.key} className="border-b px-3 py-2 text-center">{t(column.label)}</th>)}</tr></thead><tbody>{selected.rows.map((row, index) => <tr key={index} className="border-b border-slate-100">{selected.columns.map((column) => <td key={column.key} className="px-3 py-2 text-center">{row[column.key] || "—"}</td>)}</tr>)}</tbody></table></div><p className="mt-4 text-[11px] text-slate-400">{t("هذه بيانات مثال للتصميم والتجربة. ستُستبدل بحركات المخزون وأوامر الإنتاج الفعلية عند ربط وحدة المخزون.")}</p></section>
  </div></main></Layout>;
}
